### ISSUE TITLE
Translation offer DE and RU

### ISSUE THREAD

**Issue by alchemiker** [maks/Sketch-Notes#22]
Hello Maks,

Thank you very much for making this app and publishing its source code! I'm a beginner in app programming and the source code might prove useful for me. Maybe I could contribute some code later.
But at the moment I can offer to translate both the app and the play store text to German and Russian. Although I am not completely confident with russian spelling, so I would ask my cousin who lives in Russia to read it first.

Let me know if you decide to add a translation!

**Comment by maks** [comment]
@alchemiker thank you for the kind offer! 
Unfortunately SketchNotes is a very old code base, so some work needs to be done to have the text used in [preferences](https://github.com/maks/Sketch-Notes/blob/master/res/xml/preferences.xml) make use of strings defined in the [strings file](https://github.com/maks/Sketch-Notes/blob/master/res/values/strings.xml).

Also because it is such an old code base, I would not suggest learning from it on how to write an Android app in 2021.
I'm actually slowly working on a updated [rewrite of the app in Flutter](https://github.com/maks/SketchNotes2) which I would recommend as a codebase to look at to how to do clean, modern Android development.

But I'm happy for you to submit a PR with translations for `strings.xml` and you can just add there the ones for preferences too. I'm actually a native russian speaker so I can check the ru translations you submit.

**Comment by alchemiker** [comment]
@maks thank you very much for your fast reply!
I have seen Flutter mentioned before, but I thought it was just some fancy of Google to make their own programming language. But I am not an active programmer and would like to stay with Java, which is more universal, I think. 

Having never used GitHub actively, I will try as I have seen others do, to make a pull request and then ask you to merge, oк?

When I saw your user name I already thought you might be a russian (a lot of fellow russians in the web out here!), but why didn't you translate then the app just by yourself, if I might ask? Just out of curiosity.

Cheers, _alchemiker_
